name: Run cargo batch.

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Install the nightly version of rust
        run: rustup install nightly

      - name: Override the nightly version.
        run: rustup override add nightly

      - name: Add component rust-src.
        run: rustup component add rust-src

      - name: Add component llvm-tools-preview.
        run: rustup component add llvm-tools-preview

      - name: Build Shade Helper.
        run: cargo build --bin shade-helper

      - name: Perform cargo batch.
        run: cargo batch -r false
