name: Run unit-tests of Shade Helper

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Install the nightly version of rust
        run: rustup install nightly

      - name: Build Shade Helper
        run: cargo build --bin shade-helper

      - name: Perform the tests of Shade Helper
        run: cargo test --bin shade-helper
